n1 = int(input('Digite um número:'))
n2 = int(input('Digite outro número:'))
s = n1+n2
print('A soma entre {} e {} é {}'.format(n1,n2,s))
a = input('digite algo:')
print('o tipo primitivo desse valor é', type(a))
print('só tem espaços?', a.isspace())
print ('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiusculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())
print('='*20)
nome = input('Qual é o seu nome? ')
print('Prazer em te conhecer{:=^20}!'.format(nome))
print('Prazer em te conhecer{:=<20}!'.format(nome))
print('Prazer em te conhecer{:=>20}!'.format(nome))